### ISSUE TITLE
Getting Error When Trying To View Individual Blocks

### ISSUE THREAD

**Issue by apbendi** [janoside/btc-rpc-explorer#45]
visiting an individual block url, such as `http://127.0.0.1:3002/block-height/535967`, results in the following error:

```
/Users/redacted/Development/btc-rpc-explorer/views/includes/transaction-io-details.pug:10 8| each txInput, txInputIndex in txInputs 9| if (txInput) > 10| - var vout = txInput.vout[tx.vin[txInputIndex].vout]; 11| if (vout.value) 12| - totalInputValue = totalInputValue.plus(new Decimal(vout.value)); 13| Cannot read property 'undefined' of undefined

TypeError: /Users/redacted/Development/btc-rpc-explorer/views/includes/transaction-io-details.pug:10
    8| each txInput, txInputIndex in txInputs
    9| 	if (txInput)
  > 10| 		- var vout = txInput.vout[tx.vin[txInputIndex].vout];
    11| 		if (vout.value)
    12| 			- totalInputValue = totalInputValue.plus(new Decimal(vout.value));
    13| 

Cannot read property 'undefined' of undefined
    at eval (eval at wrap (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1145:24)
    at eval (eval at wrap (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1170:4)
    at eval (eval at wrap (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2483:4)
    at template (eval at wrap (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2900:72)
    at Object.exports.renderFile (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/Users/redacted/Development/btc-rpc-explorer/app.js:39:23)
    at View.render (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/response.js:1008:7)
    at /Users/redacted/Development/btc-rpc-explorer/routes/baseActionsRouter.js:405:8
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

As a sanity check, the RPC calls to my node for `getblockhash` and `getblock` work fine via `curl`. Running macOS Sierra. Any thoughts?

Thanks for a great tool!

**Comment by janoside** [comment]
@apbendi Can you check what your latest commit is? Trying to reproduce on the demo site I'm not seeing the error for that particular block: https://btc.chaintools.io/block-height/535967

Another question: do you have pruning active on your node?

Glad you're enjoying the tool!

**Comment by apbendi** [comment]
Thanks for the fast reply! I cloned master just a few minutes before reporting the issue. The issue seems to occur for all blocks-- I tried with a series of recent blocks, as well as the genesis block, and received the same error. My node is not pruning-- I'm in sync with the full chain and can run `curl` on any block to get the block data. The rest of the block explorer seems to work fine!

Just in case it matters, my node is not the same machine as the one running the explorer. The node is running Linux and is on the same LAN. The local IP of my Mac (where the explorer is running) is whitelisted in my node's config, and, as mentioned, can make RPC calls via `curl` w/o issue.

Let me know if theres anything I can do to help debug the issue on my end. Thanks!

**Comment by janoside** [comment]
Thanks for the additional info. Given the error you're seeing, your setup (linux node, mac explorer) shouldn't be the cause.

Another question: What version is your node? I'm currently running "/Satoshi:0.16.0/" both locally and on the demo server (haven't gotten around to upgrading to 0.16.2 yet)

I just pushed some code that could help in debugging. If you update to at least commit a53e92f and navigate to a block-details page I'm hoping that some of the code changes at least provide some armor against the specific error you're seeing and may give some additional debugging insight.

**Comment by apbendi** [comment]
Updated to the tip of master and re-ran. Here's what I'm seeing on the webpage itself

```
/Users/bendi/Development/btc-rpc-explorer/views/includes/transaction-io-details.pug:4 2| - var fontawesomeOutputName = "sign-out-alt"; 3| > 4| - var totalIOValues = utils.getTxTotalInputOutputValues(tx, txInputs, blockHeight); 5| 6| div(class="row") 7| div(class="col-md-6") Cannot read property 'undefined' of undefined

TypeError: /Users/bendi/Development/btc-rpc-explorer/views/includes/transaction-io-details.pug:4
    2| - var fontawesomeOutputName = "sign-out-alt";
    3| 
  > 4| - var totalIOValues = utils.getTxTotalInputOutputValues(tx, txInputs, blockHeight);
    5| 
    6| div(class="row")
    7| 	div(class="col-md-6")

Cannot read property 'undefined' of undefined
    at Object.getTxTotalInputOutputValues (/Users/bendi/Development/btc-rpc-explorer/app/utils.js:227:27)
    at eval (eval at wrap (/Users/bendi/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1129:27)
    at eval (eval at wrap (/Users/bendi/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2393:4)
    at template (eval at wrap (/Users/bendi/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2810:72)
    at Object.exports.renderFile (/Users/bendi/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/Users/bendi/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/Users/bendi/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/Users/bendi/Development/btc-rpc-explorer/app.js:39:23)
    at View.render (/Users/bendi/Development/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/bendi/Development/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/bendi/Development/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/bendi/Development/btc-rpc-explorer/node_modules/express/lib/response.js:1008:7)
    at /Users/bendi/Development/btc-rpc-explorer/routes/baseActionsRouter.js:405:8
    at process._tickCallback (internal/process/next_tick.js:109:7)
Source
```

Here's what I see in the console:

```
Running RPC Explorer for coin: Bitcoin
Connecting via RPC to node at 192.168.0.109:8332
memoryUsage: heapUsed=35.65, heapTotal=63.26, ratio=56
Using exchange rate: 6426.38615934 USD/Bitcoin starting at Fri Aug 10 2018 14:28:56 GMT-0400 (EDT)
rpc.getBlocksByHash: 00000000000000000022993c77f3b857e3c85950c590faf644b2d98885d4a480,00000000000000000003aea0e3c61ecdae718e8461c66bdf4861d6a1f80b96f1,00000000000000000015d5e8169077e4c20eedef82a5f5de1a0b11c89353a0a6,00000000000000000025fc347bc82653ba8859f86a5d375de50140e74efaa42f,0000000000000000002f0e8b8b3e3a50ebaf4208737f4710c24d3673066fd944,00000000000000000006b65ff347fe11d4360c6f23368d7b4f37007e7b13dedd,000000000000000000062b37d35907e863554a315e547285435fcea90d90d377,000000000000000000175fed3bc753be120da5ac6d93a48478afc7dfb7125567,0000000000000000001876a599898bf4f4eef5e029f2135257f60ee7e540a68c,00000000000000000011b735b8fde14db39704c446dd2b1ae4b8db198c255e0d
Starting 1-item batch JBuLpERWeizPEI0I88GX...
Executing item #1 (of 1) for batch JBuLpERWeizPEI0I88GX
Finishing batch JBuLpERWeizPEI0I88GX...
GET / 200 1008.043 ms - 30179
memoryUsage: heapUsed=78.08, heapTotal=104.19, ratio=74
GET /css/styling.css 200 5.976 ms - 1553
GET /css/radial-progress.css 200 12.153 ms - 38931
GET /img/logo/btc.svg 200 1.105 ms - 956
GET /img/logo/ltc.svg 200 1.205 ms - 391
GET /img/logo/lightning.svg 200 0.991 ms - 1149
GET /img/logo/btc.png 200 6.973 ms - 1442
GET /img/logo/btc.png 200 0.750 ms - 1442
rpc.getBlocksByHash: 00000000000000000022993c77f3b857e3c85950c590faf644b2d98885d4a480
Starting 1-item batch J299TBhPVXW6gRVoTxLv...
Executing item #1 (of 1) for batch J299TBhPVXW6gRVoTxLv
Finishing batch J299TBhPVXW6gRVoTxLv...
Starting 1-item batch ZliNDq8XKkShmVzvt7eZ...
Executing item #1 (of 1) for batch ZliNDq8XKkShmVzvt7eZ
Finishing batch ZliNDq8XKkShmVzvt7eZ...
Starting 1-item batch ekpTEwu6FSknixUWeFLH...
Executing item #1 (of 1) for batch ekpTEwu6FSknixUWeFLH
memoryUsage: heapUsed=80.61, heapTotal=105.19, ratio=76
Finishing batch ekpTEwu6FSknixUWeFLH...
GET /block-height/536137 500 4212.492 ms - 15093
```

Note the 500 response.

Also, I'm running also running `0.16.0`, as it happens. Specifically: `Bitcoin Core Daemon version v0.16.0.0-g4b4d7eb255`

Let me know if I can help more! Appreciate your fast responses.

**Comment by janoside** [comment]
Hmmm, this has me scratching my head a bit, mostly because I can't think of what could be different between your env and mine. I see some brittle, error-prone code related to the errors you're seeing, but again, I can't tell why you're seeing errors and I'm not. I'd like to improve the error-prone code, but hopefully get you up and running before that.

I have a couple more commits you can try out and let me know. I appreciate your report and your help resolving.

**Comment by apbendi** [comment]
I'll try your commits-- but it just occurred to me I'm on a rather old version of node `v7.9.0`. Any chance this could be part of the problem?

**Comment by apbendi** [comment]
So this is very weird! I updated to node 10.x and also pulled down your latest commits. I'm still seeing errors, but now it's about 50% of the time. The rest seem to work.

```
/Users/redacted/Development/btc-rpc-explorer/views/includes/transaction-io-details.pug:4 2| - var fontawesomeOutputName = "sign-out-alt"; 3| > 4| - var totalIOValues = utils.getTxTotalInputOutputValues(tx, txInputs, blockHeight); 5| 6| div(class="row") 7| div(class="col-md-6") Cannot read property 'length' of undefined

TypeError: /Users/redacted/Development/btc-rpc-explorer/views/includes/transaction-io-details.pug:4
    2| - var fontawesomeOutputName = "sign-out-alt";
    3| 
  > 4| - var totalIOValues = utils.getTxTotalInputOutputValues(tx, txInputs, blockHeight);
    5| 
    6| div(class="row")
    7| 	div(class="col-md-6")

Cannot read property 'length' of undefined
    at Object.getTxTotalInputOutputValues (/Users/redacted/Development/btc-rpc-explorer/app/utils.js:220:29)
    at eval (eval at wrap (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1129:27)
    at eval (eval at wrap (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2531:4)
    at template (eval at wrap (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2948:72)
    at Object.exports.renderFile (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/Users/redacted/Development/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/Users/redacted/Development/btc-rpc-explorer/app.js:39:23)
    at View.render (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/redacted/Development/btc-rpc-explorer/node_modules/express/lib/response.js:1008:7)
    at /Users/redacted/Development/btc-rpc-explorer/routes/baseActionsRouter.js:439:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by janoside** [comment]
Interesting. So do you mean that you can refresh the same page and it will work 50% of the time, or that 50% of blocks that you view result in errors? I'm hoping for the latter option, in which case I have a handle on something concrete. There's another commit you can try which I'm hoping could get you most of the way there while I address the remaining issue.

**Comment by janoside** [comment]
Eh...I'm doubting the idea I had a little bit ago. But still let me know about the latest commits.

**Comment by apbendi** [comment]
I should have some time to play with this again tomorrow and I'll let you know. Thanks!

**Comment by janoside** [comment]
@apbendi Any update on this?

**Comment by apbendi** [comment]
Hey @janoside, gonna look into it this afternoon. Thanks for your patience!

**Comment by apbendi** [comment]
So, embarrassingly, I had a typo in my `bitcoin.conf` file such that `txindex` was not turned on. Currently reindexing my blocks. The reason it worked sometime is that transactions that were still/recently in the mempool would return. When blocks got stale, it would fail.

One useful thing here, for other dummies like me, might be to look for the error message returned by the node when asking for a transaction that is not indexed, and then display something helpful in the UI. Anyway, closing this issue out.

By the way, I wrote up a guide for running a full node as a developer, and included running your explorer as part of it. Thought you might enjoy: https://www.buildblockchain.tech/blog/btc-node-developers-guide

Thanks for an awesome tool! Cheers!

**Comment by janoside** [comment]
Ah-ha! Thanks for the update. I'm glad we got to the bottom of this. I like your idea concerning the error-message detail and created #50 to track it. Thanks so much for your full-node-with-explorer guide...that's awesome!
